language: node_js

node_js:
  - "6"

branches:
  only:
  - master

install:
  - npm install

script:
  - hexo clean
  - hexo generate

after_success:
  - cd public
  - git init
  - git add .
  - git -c user.name='travis' -c user.email='travis' commit -m "Update blog $(date +%Y-%m-%d,%H:%M:%S)"
  - git push -f "https://athrunsun:${GITHUB_API_TOKEN}@github.com/athrunsun/blog.git" master:gh-pages
