language: node_js

node_js:
  - "6"

branches:
  only:
  - master

install:
  - npm install

script:
  - hexo clean
  - hexo generate

after_success:
  - cd public
  - git init
  - git add .
  - git -c user.name='travis' -c user.email='travis' commit -m init
  - git push -f -q https://athrunsun:$GITHUB_API_KEY@github.com/athrunsun/blog master:gh-pages &2>/dev/null
