# CDN for mathjax
location:

# style
style:
  scheme: 'now'
  #bg_img: /img/bg.png
  avatar: /img/athrun-logo.png
  slogan: "GEEK OR DIE!"
  hoverable: true

# HTML head
head:
  favicon: /img/athrun-logo.png
  high_res_favicon: /img/athrun-logo.png
  apple_touch_icon: /img/athrun-logo.png
  keywords: blog, hexo, mdui

# color
color:
  primary_color: "indigo"
  accent_color: "blue"
  layout:
  random:
  bg_color: "#eeeeee"

# appbar
appbar:
  title: "GEEK OR DIE!"
  search: true

index:
  welcome: "Did you GEEK today?"
  notification: false

# post settings
post:
  entry_excerpt: 80
  qr_code: true
  prism:
    theme: "solarizedlight"
    line_number: true
  license:
    name: 'CC BY-NC-SA 4.0'
    link:  'https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh'
  word_count: true
  read_time:
  donate:
#    wechat:
#      link: /img/avatar.png
#      fa: 'fa-wechat'
#    paypay:
#      link: 'https://paypal.com'
#      fa: 'fa-paypal'


share_menu:
 rss: true
 weibo: true
 twitter: true
 facebook: true
 googleplus: true
 linkedin: true
 qq: true
 telegram: true

comment:
    use: disqus
    shortname: okampfer

# pagination
# github@zllovesuki
pagination: 2

# footer
footer:
  since: 2016
  ICP:
  image:

# Plugins
busuanzi:
#  all_site_uv: true
#  post_pv: true
#  busuanzi_pure_mini_js: "//dn-lbstatics.qbox.me/busuanzi/2.3/busuanzi.pure.mini.js"

service_woker:

about_me: false

pace: false

random_pics: false

pages:
#  Test1:
#    link: "/myfriends"
#    md: "&#xe0ba;"
#  Test2:
#    link: "/apply-for-link"
#    fa: "fa-child"
#  Test3:
#    link: "/timeline"
#    md: "home"
#  Test4:
#    cascade: true
#    md: 'home'
#    pages:
#      TEST1:
#        link: "/myfriends"
#        md: "&#xe5ca;"
#      TEST2:
#        link: "/timeline"
#        md: "home"

sns:
 Facebook:
   link: https://facebook.com/okampfer
   fa: 'fa-facebook'

# Vendors
vendors:
  fonts_min_css:
  style_min_css:
  js_min_js:
  outdatedbrowser_min_js:
  pace_min_js:
  pace_style_css:
